---
title: "Debugging Lab"
output: 
   learnr::tutorial:
      css: css/custom-styles.css
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(error = TRUE)
knitr::knit_engines$set(python = reticulate::eng_python)

library(shiny)
library(gradethis)
library(learnr)
library(reticulate)

custom_checker <- function(label, user_code, solution_code, envir_result, evaluate_result, last_value, stage, ...) {
  if (stage == "code_check") {
      if (user_code == solution_code){
          return(list(message = random_praise(), correct = TRUE))
      }
    return(list(message = random_encouragement(), correct = FALSE))
  }
}

gradethis_setup()
tutorial_options(exercise.completion = FALSE, exercise.checker = custom_checker)
```

```{r header, echo = FALSE}
library(htmltools)

tags$div(
  class = "topContainer",
  tags$div(
    class = "logoAndTitle",
    tags$img(
      src = "./images/dsi_logo.png",
      alt = "DSI Logo",
      class = "topLogo"
    ),
    tags$h1("Data 119 - Debugging Your Code", class = "pageTitle")
  )
)
```

## Goals

The goal of this lab is to learn about common error messages and practice debugging your code.

## Setup

For this lab, we will be using the `numpy` and `math` modules.

```{python setup-packages, exercise=TRUE, exercise.eval = FALSE}
import numpy as np
import math
```

## What is a bug?

**Debugging** - the process of identifying and fixing 'bugs' in your code

**Bug** - computer science term for an error

These may either
- cause your code to produce an error message or
- cause your code to produce incorrect results (**logical errors**)

## Error Messages

There are many types of error messages you might encounter when using Python.

In general there are two main types:

- **Syntax Errors** - made before execution
    - SyntaxError
    
- **Exceptions** - made during execution
    - NameError
    - IndexError
    - AttributeError
    - KeyError
    - ImportError
    - TypeError
    - ValueError
    - ModuleNotFoundError
    - ...
    
## Syntax Errors

You will see a message starting with `SyntaxError`

Typically includes:
- file name or cell input number
- line number
- arrows pointing to the issue

The issue could be that something is missing...

```{python syntax1, exercise=TRUE, exercise.eval = FALSE}
for i in [1,2]
    print(i+8)
```

or that something was written incorrectly.

```{python syntax2, exercise=TRUE, exercise.eval = FALSE}
for i in [1,2],
    print(i+8)
```

Sometimes, the software you are using will try to warn you about syntax errors ahead of time using red or yellow lines underneath problematic parts of your code. This does not show up in this lab setup, but if you copy and past the code below into Jupyter or VSCode, you will see these lines.

```{python syntax3, exercise=TRUE, exercise.eval = FALSE}
mean([1,2,3,4)
```

When Python sees a for-loop, it expects to see a colon. When it sees an open bracket, it expects to see a closed bracket.

It does not execute the code if the syntax is incorrect

Sometimes you may get special types of `SyntaxErrors` 

A common one is the `IndentationError` - occurs when you don't have the proper indentation in a for-loop, function, etc

```{python syntax4, exercise=TRUE, exercise.eval = FALSE}
for i in [1,2]:
print(i+1)
```

Once your code is free of syntax errors, it will be executed.

During execution, you could receive other error messages known as exceptions.

## Exceptions

You will see a message starting with the exception type (eg `NameError`)

Typically includes:
- file name or cell input number
- line number
- a brief explanation
- **traceback** - the context in which the exception occurred 
    - usually in the form of a few lines of code
    - more common when you write functions

The exception type should give you clues as to what went wrong. 

:::: {.notebox}
::: {.center}
**Note:**
:::
Because we are working in a Shiny environment there is also a line that says "Run reticulate::py_last_error() for details." You may ignore this, it is not relevant to you.
:::

```{python exception1, exercise=TRUE, exercise.eval = FALSE}
print(my_string)
```

```{python exception2, exercise=TRUE, exercise.eval = FALSE}
5 + "6"
```

```{python exception3, exercise=TRUE, exercise.eval = FALSE}
a = 1 + 2
c = a + b
```

Let's walk through some exception types and what they mean...

We've already seen `NameError` and `TypeError`

`NameError`s occur when you try to use a variable name that hasn't been assigned yet

- common when running cells out of order or when you've restarted your Kernel

`TypeError`s occur when you use the wrong data type for whatever function or operand you are using

- common when you don't know the datatype of a DataFrame column (ie "2016" looks like 2016)

Can be useful to use functions like `type()` or `dtype()`
- `type()` gives you the data type but, if used on a collection of data, will only give you the type of container (ie array, series, ...)
- `dtype()` gives you the data type of the *elements* inside the container

```{python types, exercise=TRUE, exercise.eval=FALSE}
print(type("2016"), type(np.array([1, 2, 3])), np.array([1, 2, 3]).dtype)
```

### Lookup Errors

`IndexError` and `KeyError` are both types of exceptions called `LookupErrors`

They occur when you try to access a dictionary with a key that is invalid or use an invalid index for an array or DataFrame etc

Common when: 
- you use groupby and forget you have a new index
- you forget Python indexes start at 0
- if you just mistype 

```{python lookup1, exercise=TRUE, exercise.eval = FALSE}
my_dict = {"a":1, "b":2, "c":3}
my_dict[1]
```

```{python lookup2, exercise=TRUE, exercise.eval = FALSE}
my_list = [1,2,3]
my_list[3]
```

We will discuss two more common error types, but keep in mind that there are more.

These all come from base Python, but imported modules can have their own error types as well!

`AttributeError`s occur when there has been a failure to set or access an attribute
- common when the object you're working with does not actually have that attribute
- can happen if you forget parentheses on a method

```{python lookup3, exercise=TRUE, exercise.eval = FALSE, exercise.setup = 'lookup2'}
my_list.size
```

```{python lookup4, exercise=TRUE, exercise.eval = FALSE, exercise.setup = 'lookup2'}
my_list.mean
```

`ValueError`s occur when an invalid value is given to a function or operand.
- common when using mathematical functions

```{python lookup5, exercise=TRUE, exercise.eval = FALSE}
import math
math.sqrt(-1)
```

```{python lookup6, exercise=TRUE, exercise.eval = FALSE}
float("number")
```

### Logical Errors

Sometimes your code does not encounter an exception, but you don't get the output that you expected. 

This is common, especially when writing your own functions (which you will do tomorrow)

Here is an example:

```{python logical1, exercise=TRUE, exercise.eval = FALSE}
def my_min(my_array):
    '''A function that takes in an array of numbers and returns the smallest number'''
    smallest = 10
    for number in my_array:
        if number < smallest:
            smallest = number
    return smallest

my_min(np.array([6,3,2,5]))
```

```{python logical2, exercise=TRUE, exercise.eval = FALSE, exercise.setup = 'logical1'}
my_min(np.array([23,47,13,78]))
```

This function isn't giving me the answer I would expect...

I need to look at the code inside my function to see what is wrong

```
smallest = 10
for number in my_array:
    if number < smallest:
        smallest = number
```

It can be useful to do a few things when trying to debug code:
1) Think through the logic without worrying about the code itself. Should this approach work?
    - Sometimes we write 'pseudocode' or draw diagrams
2) Add print statements to see what is happening throughout the code
    - Where are things changing?
    - It works as expected until which line?
    - If you are using conditionals, is the condition ever met?
    - If you are using loops, is the loop working the way you expect?
    

```{python logical3, exercise=TRUE, exercise.eval = FALSE}
def my_min(my_array):
    '''A function that takes in an array of numbers and returns the smallest number'''
    smallest = 10
    for number in my_array:
        print("The number is: ",number)
        print("The smallest so far is: ",smallest)
        if number < smallest:
            print("I made it into the if-statement")
            smallest = number
    return smallest

my_min(np.array([23,47,13,78]))
```

From my print statements, I can tell
- the loop is iterating over the array correctly
- the smallest number is always 10
- the condition for my if-statement was never met

10 is smaller than all of the numbers in my array so `smallest` never gets set to anything else

we should initialize `smallest` to be something much larger than 10


```{python logical5, exercise=TRUE, exercise.eval = FALSE}
def my_min(my_array):
    '''A function that takes in an array of numbers and returns the smallest number'''
    smallest = math.inf
    for number in my_array:
        if number < smallest:
            smallest = number
    return smallest

my_min(np.array([23,47,13,78]))
```

## Debugging Activity

Now, you try! Find and fix the syntax errors, exceptions, and logical errors in the code blocks below.

No peaking at the answers!!

1. Debug this combination of shapes and colors.

```{python q1, exercise=TRUE, exercise.eval = TRUE, warning = FALSE, message = FALSE, exercise.setup = "setup-packages"}
shapes = ["circle", "square", "rectangle", "triangle", "rhombus",]
colors = ["red", "green", "blue"]
for i in range(5):
for j in range(3):
    print("A group of " + colors[i] + " " + shape[j] + "s")
```    

```{python q1-solution, message = FALSE, warning = FALSE, echo = FALSE}
shapes = ["circle", "square", "rectangle", "triangle", "rhombus"]
colors = ["red", "green", "blue"]
for i in range(5):
    for j in range(3):
        print("A group of " + colors[j] + " " + shapes[i] + "s")
```

```{r q1-code-check, message = FALSE, warning = FALSE, echo = FALSE}
grade_this_code()
```  
    
2. Debug this set of factorials.
    
```{python q2, exercise=TRUE, exercise.eval = TRUE, warning = FALSE, message = FALSE, exercise.setup = "setup-packages"}
number = 5
 factorial = 1

for i in range(1, number);
    factorial = factorial * "i"

print(f"The factorial of {number} is {factorial")
```        

```{python q2-solution, message = FALSE, warning = FALSE, echo = FALSE}
number = 5
factorial = 1

for i in range(1, number+1):
    factorial = factorial * i

print(f"The factorial of {number} is {factorial}")
```

```{r q2-code-check, message = FALSE, warning = FALSE, echo = FALSE}
grade_this_code()
```  

3. Debug this sum of even numbers.

```{python q3, exercise=TRUE, exercise.eval = TRUE, warning = FALSE, message = FALSE, exercise.setup = "setup-packages"}
numbers = [1 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_sum = 0

for nums in numbers
    if num % 2 == 0
        even_sum = even_sum + num
    else
        even_sum = even_sum - num  

print(f"The sum of all even numbers in the list is: {even_sum}")
```    

```{python q3-solution, message = FALSE, warning = FALSE, echo = FALSE}
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_sum = 0

for num in numbers:
    if num % 2 == 0:
        even_sum = even_sum + num

print(f"The sum of all even numbers in the list is: {even_sum}")
```

```{r q3-code-check, message = FALSE, warning = FALSE, echo = FALSE}
grade_this_code()
```  

