---
title: "Debugging Lab"
output: 
   learnr::tutorial:
      css: css/custom-styles.css
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(error = TRUE)
knitr::knit_engines$set(python = reticulate::eng_python)

library(shiny)
library(gradethis)
library(learnr)
library(reticulate)

custom_checker <- function(label, user_code, solution_code, envir_result, evaluate_result, last_value, stage, ...) {
  if (stage == "code_check") {
      if (user_code == solution_code){
          return(list(message = random_praise(), correct = TRUE))
      }
    return(list(message = random_encouragement(), correct = FALSE))
  }
}

gradethis_setup()
tutorial_options(exercise.completion = FALSE, exercise.checker = custom_checker)
```

```{r header, echo = FALSE}
library(htmltools)

tags$div(
  class = "topContainer",
  tags$div(
    class = "logoAndTitle",
    tags$img(
      src = "./images/dsi_logo.png",
      alt = "DSI Logo",
      class = "topLogo"
    ),
    tags$h1("Data 119 - Debugging Your Code", class = "pageTitle")
  )
)
```

## Goals

The goal of this lab is to learn about common error messages and practice debugging your code.

## Setup

For this lab, we will be using the `numpy` and `math` modules.

```{python setup-packages, exercise=TRUE, exercise.eval = FALSE}
import numpy as np
import math
```

## What is a bug?

**Debugging** - the process of identifying and fixing 'bugs' in your code

**Bug** - computer science term for an error

These may either
- cause your code to produce an error message or
- cause your code to produce incorrect results (**logical errors**)

## Error Messages

There are many types of error messages you might encounter when using Python.

In general there are two main types:

- **Syntax Errors** - made before execution
    - SyntaxError
    
- **Exceptions** - made during execution
    - NameError
    - IndexError
    - AttributeError
    - KeyError
    - ImportError
    - TypeError
    - ValueError
    - ModuleNotFoundError
    - ...
    
## Syntax Errors

You will see a message starting with `SyntaxError`

Typically includes:
- file name or cell input number
- line number
- arrows pointing to the issue

The issue could be that something is missing...

```{python syntax1, exercise=TRUE, exercise.eval = FALSE}
for i in [1,2]
    print(i+8)
```

or that something was written incorrectly.

```{python syntax2, exercise=TRUE, exercise.eval = FALSE}
for i in [1,2],
    print(i+8)
```

Sometimes, the software you are using will try to warn you about syntax errors ahead of time using red or yellow lines underneath problematic parts of your code. This does not show up in this lab setup, but if you copy and past the code below into Jupyter or VSCode, you will see these lines.

```{python syntax3, exercise=TRUE, exercise.eval = FALSE}
mean([1,2,3,4)
```

When Python sees a for-loop, it expects to see a colon. When it sees an open bracket, it expects to see a closed bracket.

It does not execute the code if the syntax is incorrect

Sometimes you may get special types of `SyntaxErrors` 

A common one is the `IndentationError` - occurs when you don't have the proper indentation in a for-loop, function, etc

```{python syntax4, exercise=TRUE, exercise.eval = FALSE}
for i in [1,2]:
print(i+1)
```

Once your code is free of syntax errors, it will be executed.

During execution, you could receive other error messages known as exceptions.

## Exceptions

You will see a message starting with the exception type (eg `NameError`)

Typically includes:
- file name or cell input number
- line number
- a brief explanation
- **traceback** - the context in which the exception occurred 
    - usually in the form of a few lines of code
    - more common when you write functions

The exception type should give you clues as to what went wrong. 

:::: {.notebox}
::: {.center}
**Note:**
:::
Because we are working in a Shiny environment there is also a line that says "Run reticulate::py_last_error() for details." You may ignore this, it is not relevant to you.
::::

```{python exception1, exercise=TRUE, exercise.eval = FALSE}
print(my_string)
```

```{python exception2, exercise=TRUE, exercise.eval = FALSE}
5 + "6"
```

```{python exception3, exercise=TRUE, exercise.eval = FALSE}
a = 1 + 2
c = a + b
```

Let's walk through some exception types and what they mean...

We've already seen `NameError` and `TypeError`

`NameError`s occur when you try to use a variable name that hasn't been assigned yet

- common when running cells out of order or when you've restarted your Kernel

`TypeError`s occur when you use the wrong data type for whatever function or operand you are using

- common when you don't know the datatype of a DataFrame column (ie "2016" looks like 2016)

Can be useful to use functions like `type()` or `dtype()`
- `type()` gives you the data type but, if used on a collection of data, will only give you the type of container (ie array, series, ...)
- `dtype()` gives you the data type of the *elements* inside the container

```{python types, exercise=TRUE, exercise.eval=FALSE}
print(type("2016"), type(np.array([1, 2, 3])), np.array([1, 2, 3]).dtype)
```

### Lookup Errors

`IndexError` and `KeyError` are both types of exceptions called `LookupErrors`

They occur when you try to access a dictionary with a key that is invalid or use an invalid index for an array or DataFrame etc

Common when: 
- you use groupby and forget you have a new index
- you forget Python indexes start at 0
- if you just mistype 

```{python lookup1, exercise=TRUE, exercise.eval = FALSE}
my_dict = {"a":1, "b":2, "c":3}
my_dict[1]
```

```{python lookup2, exercise=TRUE, exercise.eval = FALSE}
my_list = [1,2,3]
my_list[3]
```

We will discuss two more common error types, but keep in mind that there are more.

These all come from base Python, but imported modules can have their own error types as well!

`AttributeError`s occur when there has been a failure to set or access an attribute
- common when the object you're working with does not actually have that attribute
- can happen if you forget parentheses on a method

```{python lookup3, exercise=TRUE, exercise.eval = FALSE, exercise.setup = 'lookup2'}
my_list.size
```

```{python lookup4, exercise=TRUE, exercise.eval = FALSE, exercise.setup = 'lookup2'}
my_list.mean
```

`ValueError`s occur when an invalid value is given to a function or operand.
- common when using mathematical functions

```{python lookup5, exercise=TRUE, exercise.eval = FALSE}
import math
math.sqrt(-1)
```

```{python lookup6, exercise=TRUE, exercise.eval = FALSE}
float("number")
```

### Logical Errors

Sometimes your code does not encounter an exception, but you don't get the output that you expected. 

This is common, especially when writing your own functions (which you will do tomorrow)

Here is an example:

```{python logical1, exercise=TRUE, exercise.eval = FALSE}
def my_min(my_array):
    '''A function that takes in an array of numbers and returns the smallest number'''
    smallest = 10
    for number in my_array:
        if number < smallest:
            smallest = number
    return smallest

my_min(np.array([6,3,2,5]))
```

```{python logical2, exercise=TRUE, exercise.eval = FALSE, exercise.setup = 'logical1'}
my_min(np.array([23,47,13,78]))
```

This function isn't giving me the answer I would expect...

I need to look at the code inside my function to see what is wrong

```
smallest = 10
for number in my_array:
    if number < smallest:
        smallest = number
```

It can be useful to do a few things when trying to debug code:
1) Think through the logic without worrying about the code itself. Should this approach work?
    - Sometimes we write 'pseudocode' or draw diagrams
2) Add print statements to see what is happening throughout the code
    - Where are things changing?
    - It works as expected until which line?
    - If you are using conditionals, is the condition ever met?
    - If you are using loops, is the loop working the way you expect?
    

```{python logical3, exercise=TRUE, exercise.eval = FALSE}
def my_min(my_array):
    '''A function that takes in an array of numbers and returns the smallest number'''
    smallest = 10
    for number in my_array:
        print("The number is: ",number)
        print("The smallest so far is: ",smallest)
        if number < smallest:
            print("I made it into the if-statement")
            smallest = number
    return smallest

my_min(np.array([23,47,13,78]))
```

From my print statements, I can tell
- the loop is iterating over the array correctly
- the smallest number is always 10
- the condition for my if-statement was never met

10 is smaller than all of the numbers in my array so `smallest` never gets set to anything else

we should initialize `smallest` to be something much larger than 10


```{python logical5, exercise=TRUE, exercise.eval = FALSE}
def my_min(my_array):
    '''A function that takes in an array of numbers and returns the smallest number'''
    smallest = math.inf
    for number in my_array:
        if number < smallest:
            smallest = number
    return smallest

my_min(np.array([23,47,13,78]))
```

## Error Types Activity

Each of the code chunks below has code that would raise an error. Choose the name of the error that would be raised in the chunk. Discuss with your neighbors why these errors might appear! Then, select a possible fix. 

For example,

```{python, echo = TRUE, eval = FALSE}
15/0
```

The code in this chunk would raise a `ZeroDivision` error because you cannot divide by zero. To fix it, you might replace the zero with some other integer or float value. 

1. 

```{python, echo = TRUE, eval = FALSE}
state_capitals = {"Illinois": "Springfield", 
                  "Massachusetts": "Boston",
                  "Texas": "Austin", 
                  "Virginia": "Richmond"}

state_capitals["Washington"]
```

```{r q1a, echo=FALSE}
question(
  "What kind of error will be raised in the code chunk above?",
  answer("`AttributeError`"), 
  answer("`IndexError`"), 
  answer("`KeyError`", correct = TRUE), 
  answer("`NameError`"), 
  answer("`SyntaxError`"), 
  answer("`TypeError`"),
  answer("`ValueError`"), 
  answer("`ZeroDivisionError`"), 
  allow_retry = TRUE)
```

:::: {.discussionbox}
::: {.center}
**Discuss with a neighbor (or on Ed):**
:::

Why does this code raise that kind of error?
::::

```{r q1b, echo=FALSE}
# conditionalPanel(
#   condition = TRUE,
#   question("How would you fix this error?",
#     answer("Add a key/value pair for `Washington` and `Olympia` to the dictionary.", correct = TRUE),
#     answer("Replace the square brackets (`[]`) with parentheses (`()`)."),
#     answer("Replace `Washington` with `washington` because the keys in the dictionary should all be in lowercase."),
#     answer("Add `.loc` after `state_capitals`, because it really should be stored as a DataFrame."),
#     random_answer_order = TRUE)
# )

question("How would you fix this error?",
  answer("Add a key/value pair for `Washington` and `Olympia` to the dictionary.", correct = TRUE),
  answer("Replace the square brackets (`[]`) with parentheses (`()`)."),
  answer("Replace `Washington` with `washington` because the keys in the dictionary should all be in lowercase."),
  answer("Add `.loc` after `state_capitals`, because it really should be stored as a DataFrame."),
  random_answer_order = TRUE)
```

2. 

```{python, echo = TRUE, eval = FALSE}
state_capitals["Virginia"]]
```

```{r q2a, echo=FALSE}
question(
  "What kind of error will be raised in the code chunk above?",
  answer("`AttributeError`"), 
  answer("`IndexError`"), 
  answer("`KeyError`"), 
  answer("`NameError`"), 
  answer("`SyntaxError`", correct = TRUE), 
  answer("`TypeError`"),
  answer("`ValueError`"), 
  answer("`ZeroDivisionError`"), 
  allow_retry = TRUE)
```

:::: {.discussionbox}
::: {.center}
**Discuss with a neighbor (or on Ed):**
:::

Why does this code raise that kind of error?
::::

```{r q2b, echo=FALSE}
question("How would you fix this error?",
  answer("Remove the second close bracket (`]`).", correct = TRUE),
  answer("Add a second open bracket (`[`)."),
  answer("Replace the brackets with parentheses (`()`), because `state_capitals` should be a function."),
  answer("Add a comma after `Virginia`, because we are indexing by rows."),
  random_answer_order = TRUE)
```

3. 

```{python, echo = TRUE, eval = FALSE}
states = 50
print("There are " + states + " in the US.")
```

```{r q3a, echo=FALSE}
question(
  "What kind of error will be raised in the code chunk above?",
  answer("`AttributeError`"), 
  answer("`IndexError`"), 
  answer("`KeyError`"), 
  answer("`NameError`"), 
  answer("`SyntaxError`"), 
  answer("`TypeError`", correct = TRUE),
  answer("`ValueError`"), 
  answer("`ZeroDivisionError`"), 
  allow_retry = TRUE)
```

:::: {.discussionbox}
::: {.center}
**Discuss with a neighbor (or on Ed):**
:::

Why does this code raise that kind of error?
::::

```{r q3b, echo=FALSE}
question("How would you fix this error?",
  answer("Convert `states` to a string using `str()`.", correct = TRUE),
  answer("Use an operator other than the plus sign (`+`) for correct string/integer concatenation."),
  answer("Rewrite the entire phrase as a string, there is no need to concatenate three separate pieces.", message = "While this would work in this specific situation, it would not work in others where the sentence depends on the output of other code in your script. Therefore, it isn't the best solution!"),
  answer("Convert `There are` and ` in the US` to be integers using `int()`."),
  random_answer_order = TRUE)
```

4. 

```{python, echo = TRUE, eval = FALSE}
capitals_data = {'Capital': ["Springfield", "Boston", "Austin", "Richmond"]}
capitals_df = pd.DataFrame.from_dict(capitals_data)
capitals_df.index = ["Illinois", "Massachusetts", "Texas", "Virginia"]

capitals_df.iloc[50,]
```

```{r q4a, echo=FALSE}
question(
  "What kind of error will be raised in the code chunk above?",
  answer("`AttributeError`"), 
  answer("`IndexError`", correct = TRUE), 
  answer("`KeyError`"), 
  answer("`NameError`"), 
  answer("`SyntaxError`"), 
  answer("`TypeError`"),
  answer("`ValueError`"), 
  answer("`ZeroDivisionError`"), 
  allow_retry = TRUE)
```

:::: {.discussionbox}
::: {.center}
**Discuss with a neighbor (or on Ed):**
:::

Why does this code raise that kind of error?
::::

```{r q4b, echo=FALSE}
question("How would you fix this error?",
  answer("Change the index (`50`) to one of `0`, `1`, `2`, or `3`.", correct = TRUE),
  answer("Change the index, `50`, to `49`, because Python uses zero-based indexing."),
  answer("Change `.iloc` to `.loc`."),
  answer("Use `orient = index` in `to_dict()`."),
  random_answer_order = TRUE)
```

5. 

```{python, echo = TRUE, eval = FALSE}
capitals_df.len()
```

```{r q5a, echo=FALSE}
question(
  "What kind of error will be raised in the code chunk above?",
  answer("`AttributeError`", correct = TRUE), 
  answer("`IndexError`"), 
  answer("`KeyError`"), 
  answer("`NameError`"), 
  answer("`SyntaxError`"), 
  answer("`TypeError`"),
  answer("`ValueError`"), 
  answer("`ZeroDivisionError`"), 
  allow_retry = TRUE)
```

:::: {.discussionbox}
::: {.center}
**Discuss with a neighbor (or on Ed):**
:::

Why does this code raise that kind of error?
::::

```{r q5b, echo=FALSE}
question("How would you fix this error?",
  answer("Use `capitals_df.shape`, because `.shape` is the attribute of the DataFrame that contains the dimensions.", correct = TRUE),
  answer("Use `capitals_df.shape()`, because `.shape()` is the method for a DataFrame that will calculate the dimensions.", message = "Careful! `.shape` is an attribute; there is no such `.shape()` method."),
  answer("Use `len(capitals_df)`, because `len()` is a function and not a method."),
  answer("Use `capitals_df.length()`, because `.len()` is not the right method name."),
  random_answer_order = TRUE)
```


## Debugging Activity

Now, you try! Find and fix the syntax errors, exceptions, and logical errors in the code blocks below.

No peaking at the answers!!

1. Debug this combination of shapes and colors.

```{python q1, exercise=TRUE, exercise.eval = TRUE, warning = FALSE, message = FALSE, exercise.setup = "setup-packages"}
shapes = ["circle", "square", "rectangle", "triangle", "rhombus",]
colors = ["red", "green", "blue"]
for i in range(5):
for j in range(3):
    print("A group of " + colors[i] + " " + shape[j] + "s")
```    

```{python q1-solution, message = FALSE, warning = FALSE, echo = FALSE}
shapes = ["circle", "square", "rectangle", "triangle", "rhombus"]
colors = ["red", "green", "blue"]
for i in range(5):
    for j in range(3):
        print("A group of " + colors[j] + " " + shapes[i] + "s")
```

```{r q1-code-check, message = FALSE, warning = FALSE, echo = FALSE}
grade_this_code()
```  
    
2. Debug this set of factorials.
    
```{python q2, exercise=TRUE, exercise.eval = TRUE, warning = FALSE, message = FALSE, exercise.setup = "setup-packages"}
number = 5
 factorial = 1

for i in range(1, number);
    factorial = factorial * "i"

print(f"The factorial of {number} is {factorial")
```        

```{python q2-solution, message = FALSE, warning = FALSE, echo = FALSE}
number = 5
factorial = 1

for i in range(1, number+1):
    factorial = factorial * i

print(f"The factorial of {number} is {factorial}")
```

```{r q2-code-check, message = FALSE, warning = FALSE, echo = FALSE}
grade_this_code()
```  

3. Debug this sum of even numbers.

```{python q3, exercise=TRUE, exercise.eval = TRUE, warning = FALSE, message = FALSE, exercise.setup = "setup-packages"}
numbers = [1 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_sum = 0

for nums in numbers
    if num % 2 == 0
        even_sum = even_sum + num
    else
        even_sum = even_sum - num  

print(f"The sum of all even numbers in the list is: {even_sum}")
```    

```{python q3-solution, message = FALSE, warning = FALSE, echo = FALSE}
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_sum = 0

for num in numbers:
    if num % 2 == 0:
        even_sum = even_sum + num

print(f"The sum of all even numbers in the list is: {even_sum}")
```

```{r q3-code-check, message = FALSE, warning = FALSE, echo = FALSE}
grade_this_code()
```  

